service: wooglin-bot
app: wooglin-bot

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  environment:
    BOT_TOKEN: ${param:BOT_TOKEN}
    DEFAULT_CHANNEL: ${param:DEFAULT_CHANNEL}
    ENCRYPTION_KEY: ${param:ENCRYPTION_KEY}
    MY_ID: ${param:MY_ID}
    SECRET_PROMPT: ${param:SECRET_PROMPT}
    SECRET_RESPONSE: ${param:SECRET_RESPONSE}
    SLACK_TOKEN: ${param:SLACK_TOKEN}
    SLACK_VERIFICATION_TOKEN: ${param:SLACK_VERIFICATION_TOKEN}
    TWILIO_MESSAGING_SERVICE_SID: ${param:TWILIO_MESSAGING_SERVICE_SID}
    TWILIO_NOTIFY_SERVICE_SID: ${param:TWILIO_NOTIFY_SERVICE_SID}
    TWILIO_NUMBER: ${param:TWILIO_NUMBER}
    TWILIO_SID: ${param:TWILIO_SID}
    TWILIO_SMS_URL: ${param:TWILIO_SMS_URL}
    TWILIO_TOKEN: ${param:TWILIO_TOKEN}
    TWILIO_VERIFICATION_TOKEN: ${param:TWILIO_VERIFICATION_TOKEN}


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

# exclude the code coverage files and circle ci files
package:
  exclude:
  - .coverage
  - cover/**
  - .circleci/**

functions:
  botapi:
    handler: source/handler.wooglin_handler
    events:
      - http:
          path: /
          method: any